name = "unholy-co-website"
pages_build_output_dir = ".open-next"
compatibility_date = "2025-11-07"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
NEXT_PUBLIC_WORKER_ENDPOINT = "https://unholy-co-website.pages.dev/api/contact"
NEXT_PUBLIC_WORKER_SUBSCRIBE_ENDPOINT = "https://unholy-co-website.pages.dev/api/subscribe"
NEXT_PUBLIC_WORKER_ORDER_ENDPOINT = "https://unholy-co-website.pages.dev/api/order"
NEXT_PUBLIC_RAZORPAY_KEY_ID = "rzp_test_AbCdEf12345678"
